import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { IconSprites } from "@/ui/icon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 用于访问请求头和cookie
  const h = await headers();
  // ?? 是空值合并运算符，只处理 null/undefined
  const nonce = h.get("x-csp") ?? "";

  // 翻译模块
  // const {locale} = await loadGetInitialProps();
  // const ns = "common";
  // const translations = await loadTranslations(LocaleRouteNormalizer, ns);
  return (
    <html lang="en">
      {/* 像是把请求的nonce加在了父组件的header中 */}
      <head nonce={nonce}>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <IconSprites />
        {children}
      </body>
    </html>
  );
}
